### ISSUE TITLE
availableAnimations works on Android, not iOS

### ISSUE THREAD

**Issue by wesleycoats** [babakcode/o3d#11]
availableAnimations feature is not working on iOS. I took this same code from the pub dev page:

`availableAnimations: use controller.availableAnimations().then((animations) => log("Available animations: $animations"));
`

It gets a parse error:

```
flutter: ModelViewer initializing... <http://127.0.0.1:60021/>
flutter: ModelViewer wants to load: http://127.0.0.1:60021/
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at character 1)
(
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1247:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:912:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      jsonDecode (dart:convert/json.dart:155:10)
#7      O3dImp.availableAnimations (package:o3d/src/controllers/implementation/o3d_stub_impl.dart:86:12)
<asynchronous suspension>
#8      _MyHomePageState.build.<anonymous closure> (package:animationsample/main.dart:148:52)
<asynchronous suspension>
```

I know this GLB has animations because it works on Android:

`I/flutter (25510): Available animations: [Idle, Jump, Land, Run]`

**Comment by babakcode** [comment]
I fixed this issue in the latest version. Please upgrade the package and share your feedback.

**Comment by wesleycoats** [comment]
@babakcode I upgraded to 3.1.1 and I am still seeing this issue on iOS 

<img width="1381" alt="o3d" src="https://github.com/babakcode/o3d/assets/36309398/512146ec-bc17-4779-8ba6-2bfe4a03d566">

**Comment by babakcode** [comment]
Please upgrade to the version development and share your feedback. I fixed this issue.

**Comment by wesleycoats** [comment]
@babakcode it is working on iOS now. Thank you so much!
